### ISSUE TITLE
Constraint editor shows wrong list of features

### ISSUE THREAD

**Issue by fbenduhn** [tthuem/FeatureIDE#143]
When using Notepad-FH-Java, and creating the constraint "not cut and not undo", the constraint editor lists the following features to be dead: Cut, Undo, Cut. 

Cut should not be listed twice in this case.

**Comment by pinnecke** [comment]
Fixed it in branch for issue #97 by changing list to set. This is a sorted set which leads to nice ordering when displaying a list of dead features in constraint dialog. Please review.

**Comment by pinnecke** [comment]
In master.

**Comment by tthuem** [comment]
Problem does still occur in tool tip of constraints in feature diagram. Create constraint "not Launcher" in https://github.com/DB-SE/isp2014.marcus.pinnecke/tree/master/Aufgabe%205%20JakartaVM%20FeatureHouse

**Comment by pinnecke** [comment]
I just merged it right now.
